### PR TITLE
Modify reservation

### PR DESCRIPTION
**Pull request by StormBlade97**
#Change logs

Adds various components for the feature: `BookerInformation`, `ReservationEditionModal` etc
Some bug fixes merged from hot fixes with respect to the backend
Model rework:
* Remove pointer to event in reservation modal. This is to prevent some breaking when user delete event
* Adds id to tickets under reservations.

### CODE REVIEW

**Comment by shamnadps** [comment]
I have updated the logic for ticket update. 
1 .Please remove unnecessary files. There are atleast a couple of them.
2. Please remove the styling changes, might be a prettier config issue, it would be easier to understand.

**Comment by StormBlade97** [comment]
Yea sure

**Comment by shamnadps** [comment]
@StormBlade97  Occupied seats is not updated after the reservation is modified since it still using the ticket details from the event object which is an old one. So could you please do the changes to fetch that event/events after a reservation is modified and then we are good to go.

**Comment by shamnadps** [comment]
Also please fix the security vulnerability along with this.

**Pull request merged**
